(function(){
"use strict";
const doc=document,body=doc.body,header=doc.querySelector(".site-header");
function headerState(){if(!header)return;header.classList.toggle("is-scrolled",window.scrollY>18)}
headerState();window.addEventListener("scroll",headerState,{passive:true});
const menuToggle=doc.querySelector(".menu-toggle"),navMenu=doc.querySelector(".nav-menu"),navLinks=doc.querySelectorAll(".nav-link");
if(menuToggle&&navMenu){menuToggle.addEventListener("click",()=>{const open=navMenu.classList.toggle("is-open");menuToggle.classList.toggle("is-open",open);menuToggle.setAttribute("aria-expanded",String(open));body.classList.toggle("nav-open",open)});navLinks.forEach(l=>l.addEventListener("click",()=>{navMenu.classList.remove("is-open");menuToggle.classList.remove("is-open");menuToggle.setAttribute("aria-expanded","false");body.classList.remove("nav-open")}));doc.addEventListener("click",e=>{if(!navMenu.contains(e.target)&&!menuToggle.contains(e.target)&&navMenu.classList.contains("is-open")){navMenu.classList.remove("is-open");menuToggle.classList.remove("is-open");menuToggle.setAttribute("aria-expanded","false");body.classList.remove("nav-open")}})}
function active(){const current=window.location.pathname.split("/").pop()||"index.html";navLinks.forEach(link=>{const href=(link.getAttribute("href")||"").split("#")[0];if(href===current||(current.startsWith("article-")&&href==="insights.html"))link.classList.add("active")})}active();
const progress=doc.querySelector(".scroll-progress");function prog(){if(!progress)return;const d=doc.documentElement.scrollHeight-window.innerHeight;progress.style.width=(d>0?window.scrollY/d*100:0)+"%"}prog();window.addEventListener("scroll",prog,{passive:true});window.addEventListener("resize",prog);
const reveal=doc.querySelectorAll(".reveal");if("IntersectionObserver"in window){const ob=new IntersectionObserver((entries,o)=>{entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add("is-visible");o.unobserve(e.target)}})},{threshold:.12,rootMargin:"0px 0px -60px 0px"});reveal.forEach(el=>ob.observe(el))}else reveal.forEach(el=>el.classList.add("is-visible"));
const faqItems=doc.querySelectorAll(".faq-item");faqItems.forEach(item=>{const q=item.querySelector(".faq-question"),a=item.querySelector(".faq-answer");if(!q||!a)return;q.addEventListener("click",()=>{const open=item.classList.contains("is-open");faqItems.forEach(other=>{const oa=other.querySelector(".faq-answer"),oq=other.querySelector(".faq-question");other.classList.remove("is-open");if(oa)oa.style.maxHeight=null;if(oq)oq.setAttribute("aria-expanded","false")});if(!open){item.classList.add("is-open");a.style.maxHeight=a.scrollHeight+"px";q.setAttribute("aria-expanded","true")}})});
window.addEventListener("resize",()=>faqItems.forEach(item=>{const a=item.querySelector(".faq-answer");if(a&&item.classList.contains("is-open"))a.style.maxHeight=a.scrollHeight+"px"}));
const search=doc.querySelector("[data-blog-search]"),filters=doc.querySelectorAll("[data-filter]"),cards=doc.querySelectorAll("[data-blog-card]"),no=doc.querySelector("[data-no-results]");let activeFilter="all";const norm=v=>String(v||"").toLowerCase().trim();function updateCards(){if(!cards.length)return;const sv=norm(search?search.value:"");let count=0;cards.forEach(c=>{const title=norm(c.dataset.title),cat=norm(c.dataset.category),ex=norm(c.dataset.excerpt),kw=norm(c.dataset.keywords);const ok=(activeFilter==="all"||cat===activeFilter)&&(sv===""||title.includes(sv)||cat.includes(sv)||ex.includes(sv)||kw.includes(sv));c.style.display=ok?"":"none";if(ok)count++});if(no)no.style.display=count?"none":"block"}if(search)search.addEventListener("input",updateCards);filters.forEach(b=>b.addEventListener("click",()=>{activeFilter=norm(b.dataset.filter)||"all";filters.forEach(x=>x.classList.remove("active"));b.classList.add("active");updateCards()}));updateCards();
const form=doc.querySelector("[data-contact-form]"),msg=doc.querySelector("[data-form-message]");if(form){form.addEventListener("submit",e=>{e.preventDefault();let valid=true;form.querySelectorAll("[required]").forEach(f=>{if(!f.value.trim()){valid=false;f.classList.add("is-invalid")}else f.classList.remove("is-invalid")});if(msg){msg.textContent=valid?"Thank you. Your message has been prepared for Vane Academy(Vane Matrix Academy). Please email support@vsomllc.com for direct assistance.":"Please complete all required fields before sending your inquiry to Vane Academy(Vane Matrix Academy).";msg.classList.add("show")}if(valid)form.reset()})}
doc.querySelectorAll("[data-copy]").forEach(btn=>btn.addEventListener("click",async()=>{const v=btn.dataset.copy;if(!v)return;try{await navigator.clipboard.writeText(v);const t=btn.textContent;btn.textContent="Copied";setTimeout(()=>btn.textContent=t,1500)}catch(e){location.href="mailto:"+encodeURIComponent(v)}}));
doc.querySelectorAll("[data-current-year]").forEach(el=>el.textContent=String(new Date().getFullYear()));
doc.querySelectorAll('a[href^="http"]').forEach(a=>{if(!a.href.includes(location.hostname)){a.target="_blank";a.rel="noopener noreferrer"}});
doc.querySelectorAll("img").forEach(img=>{if(!img.hasAttribute("loading"))img.loading="lazy";if(!img.hasAttribute("decoding"))img.decoding="async"});
})();